### PR TITLE
Add .merlin files

### PR DESCRIPTION
**Pull request by ismaelga**
This is the PR for https://github.com/exercism/xocaml/issues/25

I’m not sure if the use of findlib package is ok. I’ve been using it on my machine but I don’t know if it is the recommended way to do it.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@tmcgilchrist this seems good to me, but I don't actually know what I'm looking at. What do you think?

**Comment by tmcgilchrist** [comment]
Looks reasonably good, let me try them locally this evening.

I'm curious why the hangman one has react along with the usual core and
ounit?

**Comment by tmcgilchrist** [comment]
All good from me :rocket:

**Comment by tmcgilchrist** [comment]
I should add I looked at the hangman source and realise it depends on an extra package `react` that perhaps it shouldn't? (Aside it's nifty code but perhaps not what a beginner to OCaml would know to use.) It really depends on what approach we want to take to extra packages, I'd assumed we want to just reuse the stdlib where possible. That's tricky in OCaml since the stdlib is so austere which leads to using `Core`.

**Comment by kytrinyx** [comment]
Yeah, I think standard library where possible, further dependencies where it makes sense. If OCaml programmers tend to use these other dependencies then it's probably a good idea to introduce them. I think hangman is further along in the track, so I wouldn't worry about it. I'd want to avoid extra dependencies on the first few exercises.

**Comment by daveyarwood** [comment]
I'm way late on this, but on my system, I noticed that I was getting syntastic errors about not being able to locate the module OUnit2.

Based on what I read here: https://github.com/ocaml/merlin/wiki/vim-from-scratch#using-libraries

I ran `ocamlfind list` and saw that the package name is not `ounit` but `oUnit`. Making that change in `.merlin` fixed the issue for me.

If there is interest, I'd be happy to make a PR updating the `.merlin` for each exercise to replace `ounit` with `oUnit`. Thoughts?

**Comment by kytrinyx** [comment]
> I'd be happy to make a PR updating the .merlin for each exercise to replace ounit with oUnit. Thoughts?

@daveyarwood That would be fantastic, thank you!

**Comment by daveyarwood** [comment]
Done!

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
