### PR TITLE
Rename point-mutations to hamming.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Went with the name hamming.ml/mli that seemed to match xpython (couldn't see ruby/haskell had done the rename yet) Happy with that name @kytrinyx ?
https://github.com/exercism/xocaml/issues/30

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yepp, hamming is good. Ruby has a `hamming`, it's the first exercise.

I didn't check why the build is failing, though.

**Comment by tmcgilchrist** [comment]
Weird, from the configlet:

```shell
$ bin/configlet .
Evaluating .
-> config.json does not include [point-mutations].
The command "bin/configlet ." exited with 1.
```

configlet is a binary, but I expected it would check using the `config.json` file.

**Comment by kytrinyx** [comment]
Yeah, it does use the `config.json` file, and also looks at the directories on disk. `point-mutations` should be listed under the "deprecated" key in `config.json`.

**Comment by tmcgilchrist** [comment]
Test passing, anything else needs to be done?

**Comment by kytrinyx** [comment]
Not that I know of. I'm going to run a data migration later today to make sure everyone who did point-mutations also has access to `hamming`.

**Pull request merged**
