### PR TITLE
OCaml bowling

### PR DESCRIPTION
**Pull request by stevejb71**
The bowling exercise, ported to OCaml.

I've implemented the tests in Uncle Bob's bowling game kata, but then added some more to improve the coverage. Not sure if there are too many or not.

### CODE REVIEW

**Comment by kytrinyx** [comment]
> Not sure if there are too many or not.

We've had some discussions about this—we try to aim for a test suite that pushes people to implement incrementally, without too much redundancy in the tests. There's never a perfect answer to this question, in my experience :)

**Comment by stevejb71** [comment]
To meet with your aim I should delete a few. I'll delete all but the set from the kata (the same set as in the F# exercise https://github.com/exercism/xfsharp/blob/master/exercises/bowling/BowlingTest.fs). What do you think?

On some occasions, when I've reviewed exercises that are incorrect but pass all the tests, I've added a PR to fill in the gaps. As other reviewers do that, perhaps that might be a way to discover the right set of tests for an exercise?

**Comment by kytrinyx** [comment]
I think this looks good, thank you!

> On some occasions, when I've reviewed exercises that are incorrect but pass all the tests, I've added a PR to fill in the gaps. As other reviewers do that, perhaps that might be a way to discover the right set of tests for an exercise?

Yeah, a lot of reviewers do this (thankfully), so eventually we do settle on a set of tests that seem to make the most sense. When we have a good set of tests, we try to create a JSON file containing the canonical test data for that exercise in the exercism/x-common repository (which contains metadata for all the exercises). E.g. https://github.com/exercism/x-common/blob/master/clock.json

**Comment by kytrinyx** [comment]
> I think this looks good, thank you!

And by "looks good" I meant "sounds good" :)

**Comment by stevejb71** [comment]
I removed tests - it now has the same tests as the F# exercise.

**Comment by kytrinyx** [comment]
Thanks so much @stevejb71!

**Pull request merged**
