### PR TITLE
Add tests on equal and compare to Custom-set

### PR DESCRIPTION
**Pull request by stevejb71**
Supply some tests missing from equal and compare on the Custom-set exercise.

### CODE REVIEW

**Comment by bcc32** [comment]
I'm confused.  What does it mean for one set to be "less than" another?

**Comment by stevejb71** [comment]
The example implementation does an element by element comparison in sort order. 

As an aside, haskell and scala streams don't have this function. Ocaml misses an is member and is empty function, perhaps these could replace compare if it's felt appropriate and keeps the difficulty level right.

**Comment by bcc32** [comment]
That's an odd way to compare sets.  I would support `is_member` and `is_empty` replacing `compare`.

**Comment by stevejb71** [comment]
I submitted is_member and is_empty, plus extra tests, in a separate PR.

**Pull request closed without merging**
