### PR TITLE
WIP: Create a make file that test all exercises

### PR DESCRIPTION
**Pull request by dvberkel**
When integrated with Travis CI should run test for all exercises.

### CODE REVIEW

**Comment by dvberkel** [comment]
Running make will fail because there is to much variation in the module names. The make file assume that the make exercise name is reflected back in the module name.

I will rename all modules in the test as to make this possible

**Comment by dvberkel** [comment]
The make file now successfully runs all test, except the one for prime-factors.

It depends on a module Big_int I had not available, so it is ignored at the moment. I will create an separate issue as not to loose track of the problem.

**Comment by dvberkel** [comment]
The build failed because OCaml is not installed. At least we have sensible feedback :-)

**Comment by dvberkel** [comment]
I found a [good write up](http://anil.recoil.org/2013/09/30/travis-and-ocaml.html) on how to test OCaml on Travis CI. Will look into shortly

**Comment by dvberkel** [comment]
The build is failing because the res package is moved. Filing [an issue](https://github.com/mmottl/res/issues/2) with the author made it clear that we are on an old version, of at least OPAM.

I will check the corresponding [launchpad page](https://launchpad.net/~avsm) for newer versions.

**Comment by kytrinyx** [comment]
>  At least we have sensible feedback :-)

This is great progress. Thanks so much for digging into this.

**Comment by dvberkel** [comment]
Success! Unfortunately still with a failure.

Tests are run and are failing with a missing package. I will keep adding them until all tests pass

**Comment by dvberkel** [comment]
All packages are correctly installed.

We now have a failure because the hello-world exercise has a boilerplate implementation to help others. Luckily this also fails locally.

Fixing that will bring this pull request to a close

**Comment by dvberkel** [comment]
I am ignore word-count because it gives a non reproducible compile error.

At the moment the following two exercises are ignored:
1. prime-factors
2. word-count

When this pull request lands. I will create seperate issue to include them in the test

**Pull request merged**
