### PR TITLE
Add HINTS.md file for bob exercise

### PR DESCRIPTION
**Pull request by kevgathuku**
Hey @dvberkel here's my initial attempt at solving #54 
Would you mind checking it out and leaving some feedback? Thanks 😄

### CODE REVIEW

**Comment by dvberkel** [comment]
Hi @kevgathuku, this looks fantastic! It is very thorough and a great help for people starting out with OCaml.

Eventhough this is good advice for all exercises, seeing that bob exercise is probably first encountered by new users, I think it is okay to keep it here for now.

I am willing to merge it as is, or do you want to add to it?

**Comment by kevgathuku** [comment]
@dvberkel Don't think I have anything to add at this point. 
If something else comes up, it could just be added to the file later.

**Comment by dvberkel** [comment]
@kevgathuku thanks for your contribution!

**Comment by kevgathuku** [comment]
Thanks @dvberkel for helping me make my first contribution here a smooth process 💯

**Pull request merged**
